// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package chatter.common;

public final class ChatMessagePB {
  private ChatMessagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.ChatMessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 communicationType = 1;</code>
     */
    boolean hasCommunicationType();
    /**
     * <code>required int32 communicationType = 1;</code>
     */
    int getCommunicationType();

    /**
     * <code>required string sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 2;</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>required string receviver = 3;</code>
     */
    boolean hasReceviver();
    /**
     * <code>required string receviver = 3;</code>
     */
    java.lang.String getReceviver();
    /**
     * <code>required string receviver = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceviverBytes();

    /**
     * <code>required string message = 4;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 4;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code common.ChatMessageProto}
   */
  public static final class ChatMessageProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.ChatMessageProto)
      ChatMessageProtoOrBuilder {
    // Use ChatMessageProto.newBuilder() to construct.
    private ChatMessageProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatMessageProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatMessageProto defaultInstance;
    public static ChatMessageProto getDefaultInstance() {
      return defaultInstance;
    }

    public ChatMessageProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessageProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              communicationType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sender_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              receviver_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chatter.common.ChatMessagePB.internal_static_common_ChatMessageProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chatter.common.ChatMessagePB.internal_static_common_ChatMessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              chatter.common.ChatMessagePB.ChatMessageProto.class, chatter.common.ChatMessagePB.ChatMessageProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatMessageProto> PARSER =
        new com.google.protobuf.AbstractParser<ChatMessageProto>() {
      public ChatMessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessageProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessageProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMUNICATIONTYPE_FIELD_NUMBER = 1;
    private int communicationType_;
    /**
     * <code>required int32 communicationType = 1;</code>
     */
    public boolean hasCommunicationType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 communicationType = 1;</code>
     */
    public int getCommunicationType() {
      return communicationType_;
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private java.lang.Object sender_;
    /**
     * <code>required string sender = 2;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEVIVER_FIELD_NUMBER = 3;
    private java.lang.Object receviver_;
    /**
     * <code>required string receviver = 3;</code>
     */
    public boolean hasReceviver() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string receviver = 3;</code>
     */
    public java.lang.String getReceviver() {
      java.lang.Object ref = receviver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receviver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receviver = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceviverBytes() {
      java.lang.Object ref = receviver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receviver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private java.lang.Object message_;
    /**
     * <code>required string message = 4;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      communicationType_ = 0;
      sender_ = "";
      receviver_ = "";
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommunicationType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceviver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, communicationType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSenderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReceviverBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, communicationType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSenderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReceviverBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static chatter.common.ChatMessagePB.ChatMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(chatter.common.ChatMessagePB.ChatMessageProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ChatMessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.ChatMessageProto)
        chatter.common.ChatMessagePB.ChatMessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return chatter.common.ChatMessagePB.internal_static_common_ChatMessageProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return chatter.common.ChatMessagePB.internal_static_common_ChatMessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                chatter.common.ChatMessagePB.ChatMessageProto.class, chatter.common.ChatMessagePB.ChatMessageProto.Builder.class);
      }

      // Construct using chatter.common.ChatMessagePB.ChatMessageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        communicationType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        receviver_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return chatter.common.ChatMessagePB.internal_static_common_ChatMessageProto_descriptor;
      }

      public chatter.common.ChatMessagePB.ChatMessageProto getDefaultInstanceForType() {
        return chatter.common.ChatMessagePB.ChatMessageProto.getDefaultInstance();
      }

      public chatter.common.ChatMessagePB.ChatMessageProto build() {
        chatter.common.ChatMessagePB.ChatMessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public chatter.common.ChatMessagePB.ChatMessageProto buildPartial() {
        chatter.common.ChatMessagePB.ChatMessageProto result = new chatter.common.ChatMessagePB.ChatMessageProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.communicationType_ = communicationType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receviver_ = receviver_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof chatter.common.ChatMessagePB.ChatMessageProto) {
          return mergeFrom((chatter.common.ChatMessagePB.ChatMessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(chatter.common.ChatMessagePB.ChatMessageProto other) {
        if (other == chatter.common.ChatMessagePB.ChatMessageProto.getDefaultInstance()) return this;
        if (other.hasCommunicationType()) {
          setCommunicationType(other.getCommunicationType());
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000002;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasReceviver()) {
          bitField0_ |= 0x00000004;
          receviver_ = other.receviver_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000008;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommunicationType()) {
          
          return false;
        }
        if (!hasSender()) {
          
          return false;
        }
        if (!hasReceviver()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        chatter.common.ChatMessagePB.ChatMessageProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (chatter.common.ChatMessagePB.ChatMessageProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int communicationType_ ;
      /**
       * <code>required int32 communicationType = 1;</code>
       */
      public boolean hasCommunicationType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 communicationType = 1;</code>
       */
      public int getCommunicationType() {
        return communicationType_;
      }
      /**
       * <code>required int32 communicationType = 1;</code>
       */
      public Builder setCommunicationType(int value) {
        bitField0_ |= 0x00000001;
        communicationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 communicationType = 1;</code>
       */
      public Builder clearCommunicationType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        communicationType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>required string sender = 2;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receviver_ = "";
      /**
       * <code>required string receviver = 3;</code>
       */
      public boolean hasReceviver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string receviver = 3;</code>
       */
      public java.lang.String getReceviver() {
        java.lang.Object ref = receviver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receviver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receviver = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceviverBytes() {
        java.lang.Object ref = receviver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receviver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receviver = 3;</code>
       */
      public Builder setReceviver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receviver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receviver = 3;</code>
       */
      public Builder clearReceviver() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receviver_ = getDefaultInstance().getReceviver();
        onChanged();
        return this;
      }
      /**
       * <code>required string receviver = 3;</code>
       */
      public Builder setReceviverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receviver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 4;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string message = 4;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.ChatMessageProto)
    }

    static {
      defaultInstance = new ChatMessageProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.ChatMessageProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ChatMessageProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_ChatMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatMessage.proto\022\006common\"a\n\020ChatMessa" +
      "geProto\022\031\n\021communicationType\030\001 \002(\005\022\016\n\006se" +
      "nder\030\002 \002(\t\022\021\n\treceviver\030\003 \002(\t\022\017\n\007message" +
      "\030\004 \002(\tB\037\n\016chatter.commonB\rChatMessagePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_ChatMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_ChatMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_ChatMessageProto_descriptor,
        new java.lang.String[] { "CommunicationType", "Sender", "Receviver", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
